# Hourly scraping
name: nifty50scraped

# Controls when the action will run.
on:
  push:
    branches: main


jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/checkout@v3
      with: 
        repository: shrish-shete20/Track-R-Translation
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Print working directory
      run: pwd

    # Run R script
    - name: Scrape
      run: Rscript Project-report/onlyme.R
      working-directory: Track-R-Translation
